// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MarkdownView",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v16),
        .macCatalyst(.v16),
        .macOS(.v13),
        .visionOS(.v1),
    ],
    products: [
        .library(name: "MarkdownView", targets: ["MarkdownView"]),
        .library(name: "MarkdownParser", targets: ["MarkdownParser"]),
    ],
    traits: [
        // By default every language grammar is enabled, so existing consumers
        // see no change. Opt into a subset by disabling defaults and listing
        // only the languages you need, e.g. `traits: ["Swift", "JSON"]`.
        .default(enabledTraits: [
            "Python",
            "JavaScript",
            "TypeScript",
            "Go",
            "Rust",
            "Swift",
            "C",
            "CPP",
            "Java",
            "Ruby",
            "Bash",
            "JSON",
            "HTML",
            "CSS",
            "CSharp",
            "Kotlin",
            "SQL",
            "YAML",
        ]),
        .trait(name: "Python", description: "Python syntax highlighting"),
        .trait(name: "JavaScript", description: "JavaScript syntax highlighting"),
        .trait(name: "TypeScript", description: "TypeScript and TSX syntax highlighting"),
        .trait(name: "Go", description: "Go syntax highlighting"),
        .trait(name: "Rust", description: "Rust syntax highlighting"),
        .trait(name: "Swift", description: "Swift syntax highlighting"),
        .trait(name: "C", description: "C syntax highlighting"),
        .trait(name: "CPP", description: "C++ syntax highlighting"),
        .trait(name: "Java", description: "Java syntax highlighting"),
        .trait(name: "Ruby", description: "Ruby syntax highlighting"),
        .trait(name: "Bash", description: "Bash/shell syntax highlighting"),
        .trait(name: "JSON", description: "JSON syntax highlighting"),
        .trait(name: "HTML", description: "HTML syntax highlighting"),
        .trait(name: "CSS", description: "CSS syntax highlighting"),
        .trait(name: "CSharp", description: "C# syntax highlighting"),
        .trait(name: "Kotlin", description: "Kotlin syntax highlighting"),
        .trait(name: "SQL", description: "SQL syntax highlighting"),
        .trait(name: "YAML", description: "YAML syntax highlighting"),
    ],
    dependencies: [
        .package(url: "https://github.com/mgriebling/SwiftMath", from: "1.7.3"),
        .package(url: "https://github.com/tree-sitter/swift-tree-sitter", from: "0.9.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-python", "0.23.0"..<"0.25.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-javascript", "0.23.0"..<"0.25.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-typescript", from: "0.23.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-go", from: "0.23.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-rust", from: "0.23.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-cpp", from: "0.23.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-java", from: "0.23.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-ruby", from: "0.23.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-bash", from: "0.23.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-json", from: "0.24.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-html", from: "0.23.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-css", "0.23.0"..<"0.25.0"),
        .package(url: "https://github.com/tree-sitter/tree-sitter-c-sharp", "0.23.0"..<"0.25.0"),
        .package(url: "https://github.com/fwcd/tree-sitter-kotlin", from: "0.3.8"),
        .package(url: "https://github.com/HumanInterfaceDesign/tree-sitter-swift", branch: "main"),
        .package(url: "https://github.com/HumanInterfaceDesign/tree-sitter-c", branch: "master"),
        .package(url: "https://github.com/HumanInterfaceDesign/tree-sitter-sql", branch: "main"),
        .package(url: "https://github.com/HumanInterfaceDesign/tree-sitter-yaml", branch: "master"),
        .package(url: "https://github.com/swiftlang/swift-cmark", branch: "gfm"),
    ],
    targets: [
        .target(
            name: "Litext",
            resources: [.process("Resources")]
        ),
        .target(
            name: "MarkdownView",
            dependencies: [
                "Litext",
                "MarkdownParser",
                "SwiftMath",
                .product(name: "SwiftTreeSitter", package: "swift-tree-sitter"),
                .product(name: "TreeSitterPython", package: "tree-sitter-python",
                         condition: .when(traits: ["Python"])),
                .product(name: "TreeSitterJavaScript", package: "tree-sitter-javascript",
                         condition: .when(traits: ["JavaScript"])),
                .product(name: "TreeSitterTypeScript", package: "tree-sitter-typescript",
                         condition: .when(traits: ["TypeScript"])),
                .product(name: "TreeSitterGo", package: "tree-sitter-go",
                         condition: .when(traits: ["Go"])),
                .product(name: "TreeSitterRust", package: "tree-sitter-rust",
                         condition: .when(traits: ["Rust"])),
                .product(name: "TreeSitterSwift", package: "tree-sitter-swift",
                         condition: .when(traits: ["Swift"])),
                .product(name: "TreeSitterC", package: "tree-sitter-c",
                         condition: .when(traits: ["C"])),
                .product(name: "TreeSitterCPP", package: "tree-sitter-cpp",
                         condition: .when(traits: ["CPP"])),
                .product(name: "TreeSitterJava", package: "tree-sitter-java",
                         condition: .when(traits: ["Java"])),
                .product(name: "TreeSitterRuby", package: "tree-sitter-ruby",
                         condition: .when(traits: ["Ruby"])),
                .product(name: "TreeSitterBash", package: "tree-sitter-bash",
                         condition: .when(traits: ["Bash"])),
                .product(name: "TreeSitterJSON", package: "tree-sitter-json",
                         condition: .when(traits: ["JSON"])),
                .product(name: "TreeSitterHTML", package: "tree-sitter-html",
                         condition: .when(traits: ["HTML"])),
                .product(name: "TreeSitterCSS", package: "tree-sitter-css",
                         condition: .when(traits: ["CSS"])),
                .product(name: "TreeSitterCSharp", package: "tree-sitter-c-sharp",
                         condition: .when(traits: ["CSharp"])),
                .product(name: "TreeSitterKotlin", package: "tree-sitter-kotlin",
                         condition: .when(traits: ["Kotlin"])),
                .product(name: "TreeSitterSql", package: "tree-sitter-sql",
                         condition: .when(traits: ["SQL"])),
                .product(name: "TreeSitterYAML", package: "tree-sitter-yaml",
                         condition: .when(traits: ["YAML"])),
            ],
            resources: [.process("Resources")]
        ),
        .target(name: "MarkdownParser", dependencies: [
            .product(name: "cmark-gfm", package: "swift-cmark"),
            .product(name: "cmark-gfm-extensions", package: "swift-cmark"),
        ]),
        .testTarget(
            name: "MarkdownViewTests",
            dependencies: [
                "MarkdownView",
                "MarkdownParser",
            ]
        ),
    ],
    // Preserve the Swift 5 language mode. Bumping swift-tools-version to 6.1
    // (required for traits) would otherwise default the package to the Swift 6
    // language mode and turn pre-existing concurrency warnings into errors.
    swiftLanguageModes: [.v5]
)
